name: BetterWhitelist
version: '${project.version}'
main: de.yourserver.betterwhitelist.BetterWhitelist
api-version: '1.21'
softdepend: [LuckPerms]
author: YourName
description: Konfigurierbares Whitelist-Plugin mit optionaler LuckPerms-Integration
website: https://github.com/yourname/better-whitelist

commands:
  invite:
    description: Lädt einen Spieler auf den Server ein (whitelist + LuckPerms-Gruppe)
    usage: /invite <Spielername>
    permission: invite.use
    permission-message: §cDu hast keine Berechtigung, diesen Befehl zu verwenden!
  uninvite:
    description: Entfernt einen Spieler von der Whitelist
    usage: /uninvite <Spielername>
    permission: invite.admin
    permission-message: §cDu hast keine Berechtigung, diesen Befehl zu verwenden!

permissions:
  invite.use:
    description: Erlaubt das Einladen von Spielern
    default: false
  invite.admin:
    description: Erlaubt das Entfernen von Spielern von der Whitelist
    default: false
