name: BetterWhitelist
version: '${project.version}'
main: de.yourserver.betterwhitelist.BetterWhitelist
api-version: '1.21'
softdepend: [LuckPerms]
author: YourName
description: Konfigurierbares Whitelist-Plugin mit optionaler LuckPerms-Integration
website: https://github.com/yourname/better-whitelist

commands:
  invite:
    description: Lädt einen Spieler auf den Server ein (whitelist + LuckPerms-Gruppe)
    usage: /invite <Spielername>
  uninvite:
    description: Entfernt einen Spieler von der Whitelist
    usage: /uninvite <Spielername>
  invitelist:
    description: Zeigt deine Invites an
    usage: /invitelist [Spielername]
    aliases: [ilist, invites]
  betterwhitelist:
    description: Lädt die Konfiguration neu
    usage: /betterwhitelist reload
    aliases: [bwl, bwhitelist]

permissions:
  invite.use:
    description: Erlaubt das Einladen von Spielern
    default: false
  invite.admin:
    description: Erlaubt das Entfernen von Spielern von der Whitelist
    default: false
